# Generated by Django 2.2.7 on 2020-11-20 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=50)),
                ('stock_insumo', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('formato_producto', models.CharField(choices=[('Botella 330cc', 'Botella 330cc'), ('Botella 1000cc', 'Botella 1000cc'), ('Grouler', 'Grouler'), ('Barril 30lts', 'Barril 30lts')], max_length=50)),
                ('stock_producto', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Tipo_cerveza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nombre', models.CharField(max_length=50)),
                ('caracteristicas', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Cerveza',
                'verbose_name_plural': 'Tipos de Cerveza',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cocimiento', models.DateField()),
                ('fecha_maduracion', models.DateField(blank=True)),
                ('fecha_embotellado', models.DateField(blank=True)),
                ('cantidad_litros', models.IntegerField(blank=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiponombre', to='bodega.Tipo_cerveza', verbose_name='Tipo de Cerveza')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': "Batch's",
            },
        ),
    ]
