# Generated by Django 2.2.7 on 2020-11-25 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_cerveza', to='bodega.Tipo_cerveza', verbose_name='Tipo de Cerveza'),
        ),
    ]
